version: '3.9'

services:
  classroom-db:
    image: postgres:alpine
    container_name: thesis-management-backend-classroom-db-service
    networks:
      mynet:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: thesis_management_classrooms
    ports:
      - "5433:5432"
    volumes:
      - classroom-db:/var/lib/postgresql/data
      - ./script/classroom/init-database-classroom.sql:/docker-entrypoint-initdb.d/init-database.sql
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  user-db:
    image: postgres:alpine
    container_name: thesis-management-backend-user-db-service
    networks:
      mynet:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: thesis_management_users
    ports:
      - "5436:5432"
    volumes:
      - user-db:/var/lib/postgresql/data
      - ./script/user/init-database-user.sql:/docker-entrypoint-initdb.d/init-database.sql
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"



  thesis-commitee-db:
    image: postgres:alpine
    container_name: thesis-management-backend-thesis-commitee-db-service
    networks:
      mynet:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: thesis_management_thesis_commitees
    ports:
      - "5443:5432"
    volumes:
      - thesis-commitee-db:/var/lib/postgresql/data
      - ./script/topic/init-database-thesis-commitee.sql:/docker-entrypoint-initdb.d/init-database.sql
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

  user-redis-db:
    image: redis:alpine
    container_name: thesis-management-backend-user-redis-db-service
    networks:
      mynet:
    restart: always
    environment:
      REDIS_HOST: cache
      REDIS_PASS: 
      REDIS_PORT: 6379
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes: 
      - cache:/data

  api:
    container_name: thesis-management-backend-service
    build:
      dockerfile: ./api-gw/Dockerfile
      context: .
      args:
        - image_name=apigw
    image: qthuy2k1/thesis-management-backend
    networks:
      mynet:
    ports:
      - "9091:9091"
    # links:
    #   - classroom
    #   - post
    #   - exercise
    #   - user
    #   - reporting-stage
    #   - submission
    #   - classroom-waiting-list
    #   - comment
    #   - attachment
    #   - topic
    #   - thesis-commitee
    volumes:
      - .:/usr/src/app
    # depends_on:
    #   - classroom-db
    #   - post-db
    #   - exercise-db
    #   - user-db
    #   - reporting-stage-db
    #   - submission-db
    #   - classroom-waiting-list-db
    #   - comment-db
    #   - attachment-db
    #   - topic-db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  classroom:
    container_name: thesis-management-backend-classroom-service
    build:
      dockerfile: ./classroom-svc/Dockerfile
      context: .
    image: qthuy2k1/thesis-management-backend-classroom
    networks:
      mynet:
    depends_on:
      - classroom-db
    volumes:
      - .:/usr/src/app

 
  user:
    container_name: thesis-management-backend-user-service
    env_file:
      - .env
    build:
      dockerfile: ./user-svc/Dockerfile
      context: .
    image: qthuy2k1/thesis-management-backend-user
    networks:
      mynet:
    depends_on:
      - user-db
    volumes:
      - .:/usr/src/app


  authorization:
    container_name: thesis-management-backend-authorization-service
    build:
      dockerfile: ./authorization-svc/Dockerfile
      context: .
    image: qthuy2k1/thesis-management-backend-authorization
    networks:
      mynet:
    volumes:
      - .:/usr/src/app

  thesis-commitee:
    container_name: thesis-management-backend-thesis-commitee-service
    env_file:
      - .env
    build:
      dockerfile: ./thesis-commitee-svc/Dockerfile
      context: .
    image: qthuy2k1/thesis-management-backend-thesis-commitee
    networks:
      mynet:
    depends_on:
      - thesis-commitee-db
    volumes:
      - .:/usr/src/app

  # redis:
  #   container_name: thesis-management-backend-redis-service
  #   env_file:
  #     - .env
  #   build:
  #     dockerfile: ./redis-svc/Dockerfile
  #     context: .
  #   image: qthuy2k1/thesis-management-backend-redis
  #   networks:
  #     mynet:
  #   volumes:
  #     - .:/usr/src/app

  schedule:
    container_name: thesis-management-backend-schedule-service
    # build:
    #   dockerfile: ./schedule-svc/Dockerfile
    #   context: .
    image: qthuy2k1/thesis-management-backend-schedule
    networks:
      mynet:
    # depends_on:
    #   - thesis-commitee-db
    volumes:
      - .:/usr/src/app

  upload:
    container_name: thesis-management-backend-upload-service
    env_file:
      - .env
    build:
      dockerfile: ./upload-svc/Dockerfile
      context: .
    image: qthuy2k1/thesis-management-backend-upload
    networks:
      mynet:
    ports:
      - "8083:8083"
    tty: true
    stdin_open: true
    volumes:
      - .:/usr/src/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
  apigw-client:
    container_name: thesis-management-backend-apigw-client-service
    build:
      dockerfile: ./apigw-client/Dockerfile
      context: .
    image: qthuy2k1/thesis-management-backend-apigw-client
    networks:
      mynet:
    depends_on:
      - api
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    links:
      - api
      - classroom
      - user
      - authorization
      - thesis-commitee
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  classroom-db:
  user-db:
  thesis-commitee-db:
  cache:
networks:
  mynet: