version: '3.9'

services:
  classroom-db:
    image: postgres:alpine
    container_name: classroom-db
    networks:
      mynet:
    environment:
      POSTGRES_USER: post
      POSTGRES_PASSWORD: root
      POSTGRES_DB: thesis_management_classrooms
    ports:
      - "5433:5432"
    volumes:
      - classroom-db:/var/lib/postgresql/data
      - ./script/classroom/init-database-classroom.sql:/docker-entrypoint-initdb.d/init-database.sql
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  post-db:
    image: postgres:alpine
    container_name: post-db
    networks:
      mynet:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: thesis_management_posts
    ports:
      - "5434:5432"
    volumes:
      - post-db:/var/lib/postgresql/data
      - ./script/post/init-database-post.sql:/docker-entrypoint-initdb.d/init-database.sql
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway" 

  exercise-db:
    image: postgres:alpine
    container_name: exercise-db
    networks:
      mynet:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: thesis_management_exercises
    ports:
      - "5435:5432"
    volumes:
      - exercise-db:/var/lib/postgresql/data
      - ./script/exercise/init-database-exercise.sql:/docker-entrypoint-initdb.d/init-database.sql
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

  api:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - image_name=apigw
    image: qthuy2k1/thesis-management-backend
    networks:
      mynet:
    ports:
      - "9091:9091"
    links:
      - classroom
      - post
    volumes:
      - .:/usr/src/app
    depends_on:
      - classroom-db
      - post-db
      - exercise-db

  classroom:
    env_file:
      - ./classroom-svc/.env
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - image_name=classroom
    image: qthuy2k1/thesis-management-backend-classroom
    networks:
      mynet:
    depends_on:
      - classroom-db
    volumes:
      - .:/usr/src/app

  post:
    env_file:
      - .env
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - image_name=post
    image: qthuy2k1/thesis-management-backend-post
    networks:
      mynet:
    depends_on:
      - post-db
    volumes:
      - .:/usr/src/app

  exercise:
    env_file:
      - .env
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - image_name=exercise
    image: qthuy2k1/thesis-management-backend-exercise
    networks:
      mynet:
    depends_on:
      - exercise-db
    volumes:
      - .:/usr/src/app
    
  apigw-client:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - image_name=apigw-client
    image: qthuy2k1/thesis-management-backend-apigw-client
    networks:
      mynet:
    depends_on:
      - api
    ports:
      - "8081:8081"
    volumes:
      - .:/usr/src/app
    links:
      - api
      - classroom
      - post

volumes:
  classroom-db:
  post-db:
  exercise-db:

networks:
  mynet: