#For creating Kubernetes Deployment in the Minikube cluster
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thesis-management-backend-apigw-client-3
  labels:
    app: thesis-management-backend-apigw-client-3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: thesis-management-backend-apigw-client-3
  template:
    metadata:
      labels:
        app: thesis-management-backend-apigw-client-3
    spec:
      containers:
      - name: thesis-management-backend-apigw-client
        image: qthuy2k1/thesis-management-backend-apigw-client
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      
        

---
#For creating a Kubernetes Service in the Minikube cluster
apiVersion: v1
kind: Service
metadata:
  name: thesis-management-backend-apigw-client-service-3
spec:
  selector:
    app: thesis-management-backend-apigw-client-3
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8080